### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by jeydinpham** [DoginUwU/LooofiX#1]
May I ask what OS you're using from the screenshot? It looks so cool I wanna try it

**Comment by legotardo** [comment]
It's Linux Ubuntu with some adjusts on gnome settings

Colors by: https://catppuccin.com/
Icons by: Reversal-Purple-Dark

I'm use now this wallpaper: https://wallpapercave.com/wp/wp8629994.png 

![image](https://user-images.githubusercontent.com/59850361/204036868-9da98c04-6c43-40bb-a126-b87ccf5865a0.png)
